# 格式是crd_group/crd_version
apiVersion: jasper.com/v1beta1
kind: MyDeployment
metadata:
  name: my-nginx-app
spec:
  replicas: 5
  selector:
    matchLabels:
      run: my-nginx-app
  template:
    metadata:
      labels:
        run: my-nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.9.1
        ports:
        - containerPort: 80
